apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-datasource
  namespace: monitoring
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-service.monitoring.svc:8080
        access: proxy
        isDefault: true

